name: Python package

on: #[push]
    workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    # ------------------------------------------------------------
    # Later see about caching pip dependencies
    #   https://docs.github.com/en/actions/guides/building-and-testing-python
    # ------------------------------------------------------------
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python setup.py install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test 
      run: |
        python aux/manTests.py Z -s INFO
        python aux/manTests.py A -s ERROR
        python aux/manTests.py + -s INFO
