name: Test python package logtools
    # ------------------------------------------------------------
    # (C) Alain Lichnewsky, 2021
    #
    # For running under Github's Actions
    #
    # Script performs basic test of the Python-3 version of the package
    # including added functionality.
    # ------------------------------------------------------------

on: #[push]
    workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    # ------------------------------------------------------------
    # Later see about caching pip dependencies
    #   https://docs.github.com/en/actions/guides/building-and-testing-python
    # ------------------------------------------------------------

    - name: Ascertain configuration
      #
      #    Collect information concerning $HOME (for ~/.logtoolsrc setup)
      #                                   location of file loaded from Github/
      #    Also show $LANG ( Locale may be relevant in processing of dates )
      run: |
        echo Working dir $(pwd)
        echo Files at this location:
        ls -ltha
        echo HOME: $HOME
        echo LANG: $LANG
      #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      #    ** here :: **
      #  pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
      #  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
      #  Working dir /home/runner/work/logtools/logtools
      #  HOME: /home/runner
      #  LANG: C.UTF-8
      #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install

    - name: Install .logtoolsrc
      #
      #     File ~/.logtoolsrc is used by the package to setup defaults
      #          absence results in failure; it contains filepaths and therefore
      #          must be adapted to actual filepaths
      #
      run: |
        echo executing: aux/dot_logtoolsrc.sh $(pwd) "${HOME}/.logtoolsrc"
        aux/dot_logtoolsrc.sh $(pwd) "${HOME}/.logtoolsrc"
        echo Files in  home dir: "$HOME"
        ls -ltha ~
        
    - name: Test 
      #
      #     Test Z : runs logtools/test/test_logtools.py
      #     Test A : runs a test scenario
      #     Test + : runs all tests
      #
      #     These are redundant, ordered by increasing dependency on the
      #     environment: Z:self contained, A requires 1 data file,
      #
      #     Parameter -s ZZZ indicates logging level; INFO, ERROR and DEBUG are of interest
      #
      #     Environment variables: documented in aux/matTests.py
      #     Note that if DEBUG not set, some tests suppress error output
      run: |        
        export ZTESTPGM="logtools/test/test_logtools.py"
        export TESTDATADIR="aux/testData"
	export DEBUG="-"
        python aux/manTests.py Z -s INFO
        python aux/manTests.py A -s ERROR
        python aux/manTests.py + -s INFO
